{
	"version": 1606641093,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sandleft-sheet0.png",
		"images/sandleft-sheet1.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/castlecliffleftalt-sheet0.png",
		"images/sandhillleft-sheet0.png",
		"images/p1_stand-sheet0.png",
		"images/p1_stand-sheet1.png",
		"images/p1_stand-sheet2.png",
		"images/castlecliffleft-sheet0.png",
		"images/transparent_treasure_chest_png_picture-sheet0.png",
		"images/spritefont.png",
		"images/transparent_treasure_chest_png_picture2-sheet0.png",
		"images/flatdark-sheet0.png",
		"images/flatdark2-sheet0.png",
		"images/flatdark3-sheet0.png",
		"images/tiledbackground4.png",
		"images/gemblue-sheet0.png",
		"images/plantpurple-sheet0.png",
		"images/tiledbackground5.png",
		"images/door_closedmid-sheet0.png",
		"images/door_closedmid-sheet1.png",
		"images/door_closedtop-sheet0.png",
		"images/door_closedtop-sheet1.png",
		"images/tiledbackground6.png",
		"images/keyblue-sheet0.png",
		"images/flatdark4-sheet0.png",
		"images/button_-sheet0.png",
		"images/button_-sheet1.png",
		"images/debut-sheet0.png",
		"images/window-sheet0.png",
		"images/complete-sheet0.png",
		"images/tiledbackground7.png",
		"images/button_2-sheet0.png",
		"images/button_2-sheet1.png",
		"images/button_3-sheet0.png",
		"images/button_3-sheet1.png",
		"images/enemywalking_-sheet0.png",
		"images/enemywalking_-sheet1.png",
		"images/enemywalking_-sheet2.png",
		"images/enemyfloating_-sheet0.png",
		"images/enemyflying_-sheet0.png",
		"images/hudheart_full-sheet0.png",
		"images/keyblue2-sheet0.png",
		"images/keyblue2-sheet1.png",
		"images/rock-sheet0.png",
		"images/mushroomred-sheet0.png",
		"images/mushroombrown-sheet0.png",
		"images/sand-sheet0.png",
		"images/tiledbackground8.png",
		"images/screenshot-sheet0.png",
		"images/tiledbackground10.png",
		"images/screenshot2-sheet0.png",
		"images/spritefont2.png",
		"images/button_4-sheet0.png",
		"images/button_4-sheet1.png",
		"images/button_5-sheet0.png",
		"images/button_5-sheet1.png",
		"images/button_6-sheet0.png",
		"images/button_6-sheet1.png",
		"images/button_7-sheet0.png",
		"images/button_7-sheet1.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/2018-10-03_-_inspirational_advertising_1_-_david_fesliyan.m4a",
		"media/2018-10-03_-_inspirational_advertising_1_-_david_fesliyan.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}